name: check for secret access
on:
  workflow_call:

jobs:

  caller_repo_job:
    runs-on: ubuntu-latest
    steps:    
      - name: checkout action
        id: step3
        uses: actions/checkout@v3
      - name: file read
        id: step6
        run: |
          file_path=$(find . -name '*.json' -type f -print -quit)
          cat $file_path
          echo "jsonFilePath=$file_path" >> GITHUB_ENV
      - name: check json access
        id: step7
        run:
         cat pkp.json
      - name: save artifact
        id: step2
        uses: actions/upload-artifact@v2
        with:
         name: json-artifact
         path: |
           pkp.json    
      
  called_repo_job:
    name: get the python script file in called repo 
    runs-on: ubuntu-latest
    steps:
      - name: checkout called repo
        id: step0
        uses: actions/checkout@v3
        with:
         repository: anandu-m-s/reusableWorkflow
         path: called-workflow-repo
         ref: main
      - name: Set up Python
        id: step4
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        id: step5
        run: |
         pip install requests
      - name: call python script for zip
        id: step11
        run: |
         python called-workflow-repo/call_zip.py   
      - name: download artifact
        id: step8
        uses: actions/download-artifact@v2
        with:
         name: json-artifact 
      - name: print json in called
        id: step7
        run:
         cat pkp.json   
      - name: List downloaded files
        run: |
          # List the contents of the temporary location
          ls -l tmp
          cat tmp/pkp.zip    