name: jfrog workflow
on:
  push:

jobs:
  jfrog_job:
    name: jfrog
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        id: step1
        uses: actions/checkout@v3
      - name: Set up Python
        id: step2
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        id: step3
        run: pip install requests
      - name: call python script for zip
        id: run-python
        run: |
          python call_test.py

      - name: check if zip file generate
        if: ${{ steps.run-python.outcome == 'success' }}
        id: check-zip
        run: |
          if [[ -n ${{ steps.run-python.outputs.pkp_zip_path }} ]] && [[ -f ${{ steps.run-python.outputs.pkp_zip_path }} ]]
          then
            echo "ZIP_GENERATE=true" >> $GITHUB_OUTPUT
            echo "zip true"
          else
            echo "ZIP_GENERATE=false" >> $GITHUB_OUTPUT
            echo "zip false"
          fi

      - name: setup jfrog
        uses: jfrog/setup-jfrog-cli@v3

      - name: Push Build to Artifactory
        env:
          JF_URL: https://anandutest.jfrog.io/artifactory
          JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}
        run: |
          echo "test file" > test12.txt
          export BUILD_NAME="test-build"
          export BUILD_MODULE="test-module"
          export BUILD_NUMBER="1"
          export PATH_TO_DIRECTORY="anandu-jfrog-test"

          jf rt upload --url=$JF_URL --access-token=$JF_ACCESS_TOKEN ${{ steps.run-python.outputs.pkp_zip_path }} $PATH_TO_DIRECTORY/ --flat=true --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE

      # - name: jfrog setup
      #   id: jfrog-setup
      #   uses: jfrog/setup-jfrog-cli@v3
      #   env:
      #     JF_URL: https://anandutest.jfrog.io/artifactory/anandu-jfrog-test
      #     JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}
      # - run: |
      #     export SERVER_ID="test"
      #     jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false

      # - name: Push Build to Artifactory
      #   run: |
      #     export BUILD_NAME="pkp-build"
      #     export BUILD_MODULE="pkp-module"
      #     export BUILD_NUMBER="1"
      #     export PATH_TO_DIRECTORY="anandu-jfrog-test"
      #     jf rt upload ${{ steps.run-python.outputs.pkp_zip_path }} $PATH_TO_DIRECTORY/ --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE
