name: jfrog workflow
on:
  push:

jobs:
  jfrog_job:
    name: jfrog
    runs-on: ubuntu-latest
    steps:
      - name: setup jfrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://anandutest.jfrog.io/artifactory/support-content-generic
          JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}

      - name: connect
        run: |
          export SERVER_ID="test"
          jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
      - name: Push Build to Artifactory
        id: artifactory
        run: |
          echo "test file " > test1.txt
          export BUILD_NAME="test-build"
          export BUILD_MODULE="test-module"
          export BUILD_NUMBER="1"
          jf rt upload "test1.txt" --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE
