name: called reusable workflow with python execution with artifacts
on:
  workflow_call:

jobs:
  called_function_job:
    name: get the python script file in called repo 
    runs-on: ubuntu-latest
    steps:
      - name: checkout called repo
        id: step0
        uses: actions/checkout@v3
        with:
         repository: anandu-m-s/reusableWorkflow
         path: called-workflow-repo
         ref: main
      - name: print py file
        run: |
         cat called-workflow-repo/call_test.py
      - name: get python file
        id: pyfile
        run: |
         echo "$(cat called-workflow-repo/call_test.py)" > called_job.py
      - name: save artifact
        id: upload
        uses: actions/upload-artifact@v2
        with:
         name: python-artifact
         path: called_job.py  

  caller_repo_job:
    runs-on: ubuntu-latest
    needs: called_function_job
    steps:    
      - name: checkout action
        id: step1
        uses: actions/checkout@v3
      - name: Set up Python
        id: step2
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        id: step3
        run: pip install requests  
      - name: file read
        id: step4
        run: |
          file_path=".github/workflows/pkp.json"
          cat $file_path 
      - name: download artifact
        id: download
        uses: actions/download-artifact@v2
        with:
         name: python-artifact     
      - name: call python script
        id: step5
        run: cat called_job.py
      - name: call python script
        id: step6
        run: python called_job.py  


