name: Reusable workflow demo

on:
 workflow_call:

jobs:
 demo_job:
  name: test Reusable
  runs-on: ubuntu-latest
  steps:
   - name: checkout action
     id: step3
     uses: actions/checkout@v3
   - name: access secrets
     id: step1
     run: |
      echo "secrets in caller repo is: ${{ secrets.API_KEY }}"