name: called reusable workflow which reads file
'on':
  workflow_call:
    outputs:
      fileread:
        description: output from file
        value: null
jobs:
  file_read_job:
    name: test file reads
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        id: step1
        uses: actions/checkout@v2
      - name: read file
        id: step2
        uses: ./github/workflows@main
        with:
          path: pkp.json
      - name: print file
        run: 'echo "${{steps.step2.outputs.content}}"'
