name: called reusable workflow which reads file
on:
  workflow_call:

jobs:
  file_read_job:
    name: test file reads
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        id: step1
        uses: actions/checkout@v2
      - name: Set up Python
        id: step2
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        id: step3
        run: pip install requests  
      - name: file read
        id: step4
        run: |
          file_path=".github/workflows/pkp.json"
          cat $file_path
      - name: checkout reusable repo
        id: step5
        uses: actions/checkout@v2
        with:
         repository: anandu-ms/reusableWorkflow 
      - name: call python script
        id: step6
        run: python anandu-ms/reusableWorkflow/call_test.py


