name: called reusable workflow which reads file
on:
  workflow_call:

jobs:
  python_execution_job:
    name: test python execution
    runs-on: ubuntu-latest
    steps:
      - name: checkout called repo
        id: step0
        uses: actions/checkout@v3
        with:
         repository: anandu-ms/reusableWorkflow
         path: called-workflow-repo
         ref: main
      - name: print py file
        run: |
         cat called-workflow-repo/call_test.py   
      - name: checkout action
        id: step1
        uses: actions/checkout@v3
      - name: Set up Python
        id: step2
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        id: step3
        run: pip install requests  
      - name: file read
        id: step4
        run: |
          file_path=".github/workflows/pkp.json"
          cat $file_path 
      - name: call python script
        id: step5
        run: python 


